name: rul-da
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9.7
  - pytorch=1.10.2
  - torchvision=0.11.3
  - torchaudio=0.10.2
  - cudatoolkit=11.3.1
  - intel-openmp
  - numpy=1.21.2
  - scipy=1.7.3
  - pandas=1.3.5
  - scikit-learn=1.0.2
  - matplotlib=3.5.0
  - seaborn=0.11.0
  - h5py=3.6.0
  - pillow=8.4.0
  - pyyaml=6.0
  - pip
